/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class AccountAddressEditResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public AccountAddressEditResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public AccountAddressEditResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public AccountAddressEditResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * The address is invalid and cannot be added
     */
    
    public Object accountAddressEdit400ApplicationJSONOneOf;

    public AccountAddressEditResponse withAccountAddressEdit400ApplicationJSONOneOf(Object accountAddressEdit400ApplicationJSONOneOf) {
        this.accountAddressEdit400ApplicationJSONOneOf = accountAddressEdit400ApplicationJSONOneOf;
        return this;
    }
    
    /**
     * The address was successfully edited
     */
    
    public com.bolt.bolt_embed.models.shared.AddressListing addressListing;

    public AccountAddressEditResponse withAddressListing(com.bolt.bolt_embed.models.shared.AddressListing addressListing) {
        this.addressListing = addressListing;
        return this;
    }
    
    public AccountAddressEditResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
