/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.bolt.bolt_embed.utils.SpeakeasyMetadata;


public class AccountAddressCreateSecurity {
    @SpeakeasyMetadata("security:option=true")
    public AccountAddressCreateSecurityOption1 option1;

    public AccountAddressCreateSecurity withOption1(AccountAddressCreateSecurityOption1 option1) {
        this.option1 = option1;
        return this;
    }
    
    @SpeakeasyMetadata("security:option=true")
    public AccountAddressCreateSecurityOption2 option2;

    public AccountAddressCreateSecurity withOption2(AccountAddressCreateSecurityOption2 option2) {
        this.option2 = option2;
        return this;
    }
    
    public AccountAddressCreateSecurity(){}
}
