/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class AccountAddressCreateResponse {
    
    public String contentType;

    public AccountAddressCreateResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public AccountAddressCreateResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public AccountAddressCreateResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * The address is invalid and cannot be added
     */
    
    public Object accountAddressCreate400ApplicationJSONOneOf;

    public AccountAddressCreateResponse withAccountAddressCreate400ApplicationJSONOneOf(Object accountAddressCreate400ApplicationJSONOneOf) {
        this.accountAddressCreate400ApplicationJSONOneOf = accountAddressCreate400ApplicationJSONOneOf;
        return this;
    }
    
    /**
     * The address was successfully added
     */
    
    public com.bolt.bolt_embed.models.shared.AddressListing addressListing;

    public AccountAddressCreateResponse withAddressListing(com.bolt.bolt_embed.models.shared.AddressListing addressListing) {
        this.addressListing = addressListing;
        return this;
    }
    
    public AccountAddressCreateResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
