/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.bolt.bolt_embed.utils.SpeakeasyMetadata;


public class AccountAddressDeleteSecurity {
    @SpeakeasyMetadata("security:option=true")
    public AccountAddressDeleteSecurityOption1 option1;

    public AccountAddressDeleteSecurity withOption1(AccountAddressDeleteSecurityOption1 option1) {
        this.option1 = option1;
        return this;
    }
    
    @SpeakeasyMetadata("security:option=true")
    public AccountAddressDeleteSecurityOption2 option2;

    public AccountAddressDeleteSecurity withOption2(AccountAddressDeleteSecurityOption2 option2) {
        this.option2 = option2;
        return this;
    }
    
    public AccountAddressDeleteSecurity(){}
}
