/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.bolt.bolt_embed.utils.SpeakeasyMetadata;


public class AccountAddressEditSecurity {
    @SpeakeasyMetadata("security:option=true")
    public AccountAddressEditSecurityOption1 option1;

    public AccountAddressEditSecurity withOption1(AccountAddressEditSecurityOption1 option1) {
        this.option1 = option1;
        return this;
    }
    
    @SpeakeasyMetadata("security:option=true")
    public AccountAddressEditSecurityOption2 option2;

    public AccountAddressEditSecurity withOption2(AccountAddressEditSecurityOption2 option2) {
        this.option2 = option2;
        return this;
    }
    
    public AccountAddressEditSecurity(){}
}
