/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class AccountAddPaymentMethodResponse {
    
    public String contentType;

    public AccountAddPaymentMethodResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public AccountAddPaymentMethodResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public AccountAddPaymentMethodResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * The payment method was successfully added
     */
    
    public com.bolt.bolt_embed.models.shared.PaymentMethodCreditCard paymentMethodCreditCard;

    public AccountAddPaymentMethodResponse withPaymentMethodCreditCard(com.bolt.bolt_embed.models.shared.PaymentMethodCreditCard paymentMethodCreditCard) {
        this.paymentMethodCreditCard = paymentMethodCreditCard;
        return this;
    }
    
    public AccountAddPaymentMethodResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
