/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class AccountAddressCreateResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public AccountAddressCreateResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public AccountAddressCreateResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public AccountAddressCreateResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * The address was successfully added
     */
    
    public com.bolt.bolt_embed.models.shared.AddressListing addressListing;

    public AccountAddressCreateResponse withAddressListing(com.bolt.bolt_embed.models.shared.AddressListing addressListing) {
        this.addressListing = addressListing;
        return this;
    }
    
    /**
     * The address is invalid and cannot be added
     */
    
    public Object oneOf;

    public AccountAddressCreateResponse withOneOf(Object oneOf) {
        this.oneOf = oneOf;
        return this;
    }
    
    public AccountAddressCreateResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode, @JsonProperty("RawResponse") HttpResponse<byte[]> rawResponse) {
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
  }
}
