/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.bolt.bolt_embed.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class AccountAddressEditRequest {
    /**
     * The publicly viewable identifier used to identify a merchant division.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Publishable-Key")
    public String xPublishableKey;

    public AccountAddressEditRequest withXPublishableKey(String xPublishableKey) {
        this.xPublishableKey = xPublishableKey;
        return this;
    }
    
    @SpeakeasyMetadata("request:mediaType=application/json")
    public com.bolt.bolt_embed.models.shared.AddressListing addressListing;

    public AccountAddressEditRequest withAddressListing(com.bolt.bolt_embed.models.shared.AddressListing addressListing) {
        this.addressListing = addressListing;
        return this;
    }
    
    /**
     * The ID of the address to edit
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;

    public AccountAddressEditRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    public AccountAddressEditRequest(@JsonProperty("X-Publishable-Key") String xPublishableKey, @JsonProperty("address-listing") com.bolt.bolt_embed.models.shared.AddressListing addressListing, @JsonProperty("id") String id) {
        this.xPublishableKey = xPublishableKey;
        this.addressListing = addressListing;
        this.id = id;
  }
}
