/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.bolt.bolt_embed.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class AccountAddPaymentMethodRequest {
    /**
     * The publicly viewable identifier used to identify a merchant division.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Publishable-Key")
    public String xPublishableKey;

    public AccountAddPaymentMethodRequest withXPublishableKey(String xPublishableKey) {
        this.xPublishableKey = xPublishableKey;
        return this;
    }
    
    @SpeakeasyMetadata("request:mediaType=application/json")
    public com.bolt.bolt_embed.models.shared.PaymentMethodCreditCard paymentMethodCreditCard;

    public AccountAddPaymentMethodRequest withPaymentMethodCreditCard(com.bolt.bolt_embed.models.shared.PaymentMethodCreditCard paymentMethodCreditCard) {
        this.paymentMethodCreditCard = paymentMethodCreditCard;
        return this;
    }
    
    public AccountAddPaymentMethodRequest(@JsonProperty("X-Publishable-Key") String xPublishableKey, @JsonProperty("payment-method-credit-card") com.bolt.bolt_embed.models.shared.PaymentMethodCreditCard paymentMethodCreditCard) {
        this.xPublishableKey = xPublishableKey;
        this.paymentMethodCreditCard = paymentMethodCreditCard;
  }
}
