/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.bolt.bolt_embed.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class AccountAddPaymentMethodRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public Object requestBody;

    public AccountAddPaymentMethodRequest withRequestBody(Object requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * The publicly viewable identifier used to identify a merchant division.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Publishable-Key")
    public String xPublishableKey;

    public AccountAddPaymentMethodRequest withXPublishableKey(String xPublishableKey) {
        this.xPublishableKey = xPublishableKey;
        return this;
    }
    
    public AccountAddPaymentMethodRequest(@JsonProperty("RequestBody") Object requestBody, @JsonProperty("X-Publishable-Key") String xPublishableKey) {
        this.requestBody = requestBody;
        this.xPublishableKey = xPublishableKey;
  }
}
