/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class MerchantCallbacksGetResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public MerchantCallbacksGetResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public MerchantCallbacksGetResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public MerchantCallbacksGetResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Callbacks URLs were successfully retrieved
     */
    
    public com.bolt.bolt_embed.models.shared.CallbackUrls callbackUrls;

    public MerchantCallbacksGetResponse withCallbackUrls(com.bolt.bolt_embed.models.shared.CallbackUrls callbackUrls) {
        this.callbackUrls = callbackUrls;
        return this;
    }
    
    public MerchantCallbacksGetResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
