/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.bolt.bolt_embed.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class MerchantCallbacksUpdateRequest {
    /**
     * The publicly viewable identifier used to identify a merchant division.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Publishable-Key")
    public String xPublishableKey;

    public MerchantCallbacksUpdateRequest withXPublishableKey(String xPublishableKey) {
        this.xPublishableKey = xPublishableKey;
        return this;
    }
    
    @SpeakeasyMetadata("request:mediaType=application/json")
    public com.bolt.bolt_embed.models.shared.CallbackUrls callbackUrls;

    public MerchantCallbacksUpdateRequest withCallbackUrls(com.bolt.bolt_embed.models.shared.CallbackUrls callbackUrls) {
        this.callbackUrls = callbackUrls;
        return this;
    }
    
    public MerchantCallbacksUpdateRequest(@JsonProperty("X-Publishable-Key") String xPublishableKey, @JsonProperty("callback-urls") com.bolt.bolt_embed.models.shared.CallbackUrls callbackUrls) {
        this.xPublishableKey = xPublishableKey;
        this.callbackUrls = callbackUrls;
  }
}
