/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class MerchantCallbacksUpdateResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public MerchantCallbacksUpdateResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public MerchantCallbacksUpdateResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public MerchantCallbacksUpdateResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Callbacks URLs were successfully updated
     */
    
    public com.bolt.bolt_embed.models.shared.CallbackUrls callbackUrls;

    public MerchantCallbacksUpdateResponse withCallbackUrls(com.bolt.bolt_embed.models.shared.CallbackUrls callbackUrls) {
        this.callbackUrls = callbackUrls;
        return this;
    }
    
    /**
     * The URL is invalid and cannot be set
     */
    
    public Object oneOf;

    public MerchantCallbacksUpdateResponse withOneOf(Object oneOf) {
        this.oneOf = oneOf;
        return this;
    }
    
    public MerchantCallbacksUpdateResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode, @JsonProperty("RawResponse") HttpResponse<byte[]> rawResponse) {
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
  }
}
