/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class MerchantCallbacksUpdateResponse {
    
    public String contentType;

    public MerchantCallbacksUpdateResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public MerchantCallbacksUpdateResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public MerchantCallbacksUpdateResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * The URL is invalid and cannot be set
     */
    
    public com.bolt.bolt_embed.models.shared.CallbackUrlErrorInvalidUrl callbackUrlErrorInvalidUrl;

    public MerchantCallbacksUpdateResponse withCallbackUrlErrorInvalidUrl(com.bolt.bolt_embed.models.shared.CallbackUrlErrorInvalidUrl callbackUrlErrorInvalidUrl) {
        this.callbackUrlErrorInvalidUrl = callbackUrlErrorInvalidUrl;
        return this;
    }
    
    /**
     * Callbacks URLs were successfully updated
     */
    
    public com.bolt.bolt_embed.models.shared.CallbackUrls callbackUrls;

    public MerchantCallbacksUpdateResponse withCallbackUrls(com.bolt.bolt_embed.models.shared.CallbackUrls callbackUrls) {
        this.callbackUrls = callbackUrls;
        return this;
    }
    
    public MerchantCallbacksUpdateResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
