/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.bolt.bolt_embed.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class PaymentsInitializeRequest {
    /**
     * The publicly viewable identifier used to identify a merchant division.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Publishable-Key")
    public String xPublishableKey;

    public PaymentsInitializeRequest withXPublishableKey(String xPublishableKey) {
        this.xPublishableKey = xPublishableKey;
        return this;
    }
    
    @SpeakeasyMetadata("request:mediaType=application/json")
    public com.bolt.bolt_embed.models.shared.PaymentMethodInitializeRequest paymentMethodInitializeRequest;

    public PaymentsInitializeRequest withPaymentMethodInitializeRequest(com.bolt.bolt_embed.models.shared.PaymentMethodInitializeRequest paymentMethodInitializeRequest) {
        this.paymentMethodInitializeRequest = paymentMethodInitializeRequest;
        return this;
    }
    
    public PaymentsInitializeRequest(@JsonProperty("X-Publishable-Key") String xPublishableKey, @JsonProperty("payment-method-initialize-request") com.bolt.bolt_embed.models.shared.PaymentMethodInitializeRequest paymentMethodInitializeRequest) {
        this.xPublishableKey = xPublishableKey;
        this.paymentMethodInitializeRequest = paymentMethodInitializeRequest;
  }
}
