/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.bolt.bolt_embed.utils.SpeakeasyMetadata;


public class PaymentsInitializeSecurity {
    @SpeakeasyMetadata("security:option=true")
    public PaymentsInitializeSecurityOption1 option1;

    public PaymentsInitializeSecurity withOption1(PaymentsInitializeSecurityOption1 option1) {
        this.option1 = option1;
        return this;
    }
    
    @SpeakeasyMetadata("security:option=true")
    public PaymentsInitializeSecurityOption2 option2;

    public PaymentsInitializeSecurity withOption2(PaymentsInitializeSecurityOption2 option2) {
        this.option2 = option2;
        return this;
    }
    
    public PaymentsInitializeSecurity(){}
}
