/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class WebhooksGetResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public WebhooksGetResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public WebhooksGetResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public WebhooksGetResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * The specified resource was not found
     */
    
    public com.bolt.bolt_embed.models.shared.Error error;

    public WebhooksGetResponse withError(com.bolt.bolt_embed.models.shared.Error error) {
        this.error = error;
        return this;
    }
    
    /**
     * Webhook information has been retrieved
     */
    
    public com.bolt.bolt_embed.models.shared.Webhook webhook;

    public WebhooksGetResponse withWebhook(com.bolt.bolt_embed.models.shared.Webhook webhook) {
        this.webhook = webhook;
        return this;
    }
    
    public WebhooksGetResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
