/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class WebhooksGetAllResponse {
    
    public String contentType;

    public WebhooksGetAllResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public WebhooksGetAllResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public WebhooksGetAllResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * All existing webhook information has been retrieved
     */
    
    public WebhooksGetAll200ApplicationJSON webhooksGetAll200ApplicationJSONObject;

    public WebhooksGetAllResponse withWebhooksGetAll200ApplicationJSONObject(WebhooksGetAll200ApplicationJSON webhooksGetAll200ApplicationJSONObject) {
        this.webhooksGetAll200ApplicationJSONObject = webhooksGetAll200ApplicationJSONObject;
        return this;
    }
    
    public WebhooksGetAllResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
