/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.bolt.bolt_embed.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class WebhooksGetRequest {
    /**
     * The ID of the webhook whose information to retrieve
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;

    public WebhooksGetRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    public WebhooksGetRequest(@JsonProperty("id") String id) {
        this.id = id;
  }
}
