/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.operations;

import com.bolt.bolt_embed.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class WebhooksGetSecurity {
    @SpeakeasyMetadata("security:scheme=true,type=apiKey,subtype=header,name=X-API-Key")
    public String apiKey;

    public WebhooksGetSecurity withApiKey(String apiKey) {
        this.apiKey = apiKey;
        return this;
    }
    
    public WebhooksGetSecurity(@JsonProperty("api-key") String apiKey) {
        this.apiKey = apiKey;
  }
}
