/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.callbacks;

import com.fasterxml.jackson.annotation.JsonProperty;


public class WebhooksCreateWebhookEventRequestBody {
    @JsonProperty("message")
    public String message;

    public WebhooksCreateWebhookEventRequestBody withMessage(String message) {
        this.message = message;
        return this;
    }
    
    public WebhooksCreateWebhookEventRequestBody(@JsonProperty("message") String message) {
        this.message = message;
  }
}
