/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed;

import com.bolt.bolt_embed.utils.HTTPClient;
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;

class SDKConfiguration {
	public HTTPClient defaultClient;
	public HTTPClient securityClient;
	
	public String serverUrl;
	public int serverIdx = 0;
	List<Map<String, String>> serverDefaults = new ArrayList<Map<String, String>>(){{
		add(new HashMap<String, String>(){{
			put("username", "xwang");
		}});
		add(new HashMap<String, String>(){{
			put("environment", "api-sandbox");
		}});
	}};
	public String language = "java";
	public String openapiDocVersion = "3.0.1";
	public String sdkVersion = "0.1.0";
	public String genVersion = "2.88.1";
	
	public Map<String, String> getServerVariableDefaults() {
		return serverDefaults.get(this.serverIdx);
	}
}