/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.bolt.bolt_embed.utils.DateTimeDeserializer;
import com.bolt.bolt_embed.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;


public class AccountTestCreationDataOutput {
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("deactivate_at")
    public OffsetDateTime deactivateAt;

    public AccountTestCreationDataOutput withDeactivateAt(OffsetDateTime deactivateAt) {
        this.deactivateAt = deactivateAt;
        return this;
    }
    
    @JsonProperty("email")
    public String email;

    public AccountTestCreationDataOutput withEmail(String email) {
        this.email = email;
        return this;
    }
    
    @JsonProperty("email_state")
    public EmailState emailState;

    public AccountTestCreationDataOutput withEmailState(EmailState emailState) {
        this.emailState = emailState;
        return this;
    }
    
    @JsonProperty("oauth_code")
    public String oauthCode;

    public AccountTestCreationDataOutput withOauthCode(String oauthCode) {
        this.oauthCode = oauthCode;
        return this;
    }
    
    @JsonProperty("otp_code")
    public String otpCode;

    public AccountTestCreationDataOutput withOtpCode(String otpCode) {
        this.otpCode = otpCode;
        return this;
    }
    
    @JsonProperty("phone")
    public String phone;

    public AccountTestCreationDataOutput withPhone(String phone) {
        this.phone = phone;
        return this;
    }
    
    @JsonProperty("phone_state")
    public PhoneState phoneState;

    public AccountTestCreationDataOutput withPhoneState(PhoneState phoneState) {
        this.phoneState = phoneState;
        return this;
    }
    
    public AccountTestCreationDataOutput(@JsonProperty("deactivate_at") OffsetDateTime deactivateAt, @JsonProperty("email") String email, @JsonProperty("email_state") EmailState emailState, @JsonProperty("oauth_code") String oauthCode, @JsonProperty("otp_code") String otpCode, @JsonProperty("phone") String phone, @JsonProperty("phone_state") PhoneState phoneState) {
        this.deactivateAt = deactivateAt;
        this.email = email;
        this.emailState = emailState;
        this.oauthCode = oauthCode;
        this.otpCode = otpCode;
        this.phone = phone;
        this.phoneState = phoneState;
  }
}
