/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class Account {
    @JsonProperty("addresses")
    public AddressListing[] addresses;

    public Account withAddresses(AddressListing[] addresses) {
        this.addresses = addresses;
        return this;
    }
    
    @JsonProperty("payment_methods")
    public PaymentMethodCreditCard[] paymentMethods;

    public Account withPaymentMethods(PaymentMethodCreditCard[] paymentMethods) {
        this.paymentMethods = paymentMethods;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("profile")
    public Profile profile;

    public Account withProfile(Profile profile) {
        this.profile = profile;
        return this;
    }
    
    public Account(@JsonProperty("addresses") AddressListing[] addresses, @JsonProperty("payment_methods") PaymentMethodCreditCard[] paymentMethods) {
        this.addresses = addresses;
        this.paymentMethods = paymentMethods;
  }
}
