/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.bolt.bolt_embed.utils.DateTimeDeserializer;
import com.bolt.bolt_embed.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;


public class AccountTestCreationData {
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("deactivate_at")
    public OffsetDateTime deactivateAt;

    public AccountTestCreationData withDeactivateAt(OffsetDateTime deactivateAt) {
        this.deactivateAt = deactivateAt;
        return this;
    }
    
    @JsonProperty("email_state")
    public EmailState emailState;

    public AccountTestCreationData withEmailState(EmailState emailState) {
        this.emailState = emailState;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("has_address")
    public Boolean hasAddress;

    public AccountTestCreationData withHasAddress(Boolean hasAddress) {
        this.hasAddress = hasAddress;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_migrated")
    public Boolean isMigrated;

    public AccountTestCreationData withIsMigrated(Boolean isMigrated) {
        this.isMigrated = isMigrated;
        return this;
    }
    
    @JsonProperty("phone_state")
    public PhoneState phoneState;

    public AccountTestCreationData withPhoneState(PhoneState phoneState) {
        this.phoneState = phoneState;
        return this;
    }
    
    public AccountTestCreationData(@JsonProperty("deactivate_at") OffsetDateTime deactivateAt, @JsonProperty("email_state") EmailState emailState, @JsonProperty("phone_state") PhoneState phoneState) {
        this.deactivateAt = deactivateAt;
        this.emailState = emailState;
        this.phoneState = phoneState;
  }
}
