/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AddressReferenceExplicitTag - The type of address reference
 */
public enum AddressReferenceExplicitTag {
    EXPLICIT("explicit");

    @JsonValue
    public final String value;

    private AddressReferenceExplicitTag(String value) {
        this.value = value;
    }
}
