/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class AddressReferenceId {
    /**
     * The type of address reference
     */
    @JsonProperty(".tag")
    public AddressReferenceIdTag dotTag;

    public AddressReferenceId withDotTag(AddressReferenceIdTag dotTag) {
        this.dotTag = dotTag;
        return this;
    }
    
    /**
     * The address's ID
     */
    @JsonProperty("id")
    public String id;

    public AddressReferenceId withId(String id) {
        this.id = id;
        return this;
    }
    
    public AddressReferenceId(@JsonProperty(".tag") AddressReferenceIdTag dotTag, @JsonProperty("id") String id) {
        this.dotTag = dotTag;
        this.id = id;
  }
}
