/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AddressErrorInvalidRegionTag - The type of error returned
 */
public enum AddressErrorInvalidRegionTag {
    INVALID_REGION("invalid_region");

    @JsonValue
    public final String value;

    private AddressErrorInvalidRegionTag(String value) {
        this.value = value;
    }
}
