/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class AddressListing {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("company")
    public String company;

    public AddressListing withCompany(String company) {
        this.company = company;
        return this;
    }
    
    @JsonProperty("country_code")
    public String countryCode;

    public AddressListing withCountryCode(String countryCode) {
        this.countryCode = countryCode;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("email")
    public String email;

    public AddressListing withEmail(String email) {
        this.email = email;
        return this;
    }
    
    @JsonProperty("first_name")
    public String firstName;

    public AddressListing withFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public String id;

    public AddressListing withId(String id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_default")
    public Boolean isDefault;

    public AddressListing withIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
        return this;
    }
    
    @JsonProperty("last_name")
    public String lastName;

    public AddressListing withLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }
    
    @JsonProperty("locality")
    public String locality;

    public AddressListing withLocality(String locality) {
        this.locality = locality;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("phone")
    public String phone;

    public AddressListing withPhone(String phone) {
        this.phone = phone;
        return this;
    }
    
    @JsonProperty("postal_code")
    public String postalCode;

    public AddressListing withPostalCode(String postalCode) {
        this.postalCode = postalCode;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("region")
    public String region;

    public AddressListing withRegion(String region) {
        this.region = region;
        return this;
    }
    
    @JsonProperty("street_address1")
    public String streetAddress1;

    public AddressListing withStreetAddress1(String streetAddress1) {
        this.streetAddress1 = streetAddress1;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("street_address2")
    public String streetAddress2;

    public AddressListing withStreetAddress2(String streetAddress2) {
        this.streetAddress2 = streetAddress2;
        return this;
    }
    
    public AddressListing(@JsonProperty("country_code") String countryCode, @JsonProperty("first_name") String firstName, @JsonProperty("last_name") String lastName, @JsonProperty("locality") String locality, @JsonProperty("postal_code") String postalCode, @JsonProperty("street_address1") String streetAddress1) {
        this.countryCode = countryCode;
        this.firstName = firstName;
        this.lastName = lastName;
        this.locality = locality;
        this.postalCode = postalCode;
        this.streetAddress1 = streetAddress1;
  }
}
