/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class AddressErrorInvalidRegion {
    /**
     * The type of error returned
     */
    @JsonProperty(".tag")
    public AddressErrorInvalidRegionTag dotTag;

    public AddressErrorInvalidRegion withDotTag(AddressErrorInvalidRegionTag dotTag) {
        this.dotTag = dotTag;
        return this;
    }
    
    /**
     * A human-readable error message, which might include information specific to
     * the request that was made.
     * 
     */
    @JsonProperty("message")
    public String message;

    public AddressErrorInvalidRegion withMessage(String message) {
        this.message = message;
        return this;
    }
    
    public AddressErrorInvalidRegion(@JsonProperty(".tag") AddressErrorInvalidRegionTag dotTag, @JsonProperty("message") String message) {
        this.dotTag = dotTag;
        this.message = message;
  }
}
