/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AddressErrorInvalidPostalCodeTag - The type of error returned
 */
public enum AddressErrorInvalidPostalCodeTag {
    INVALID_POSTAL_CODE("invalid_postal_code");

    @JsonValue
    public final String value;

    private AddressErrorInvalidPostalCodeTag(String value) {
        this.value = value;
    }
}
