/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CallbackUrlErrorInvalidUrlTag - The type of error returned
 */
public enum CallbackUrlErrorInvalidUrlTag {
    INVALID_URL("invalid_url");

    @JsonValue
    public final String value;

    private CallbackUrlErrorInvalidUrlTag(String value) {
        this.value = value;
    }
}
