/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CallbackUrls {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("account_page")
    public String accountPage;

    public CallbackUrls withAccountPage(String accountPage) {
        this.accountPage = accountPage;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("base_domain")
    public String baseDomain;

    public CallbackUrls withBaseDomain(String baseDomain) {
        this.baseDomain = baseDomain;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("confirmation_redirect")
    public String confirmationRedirect;

    public CallbackUrls withConfirmationRedirect(String confirmationRedirect) {
        this.confirmationRedirect = confirmationRedirect;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("create_order")
    public String createOrder;

    public CallbackUrls withCreateOrder(String createOrder) {
        this.createOrder = createOrder;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("debug")
    public String debug;

    public CallbackUrls withDebug(String debug) {
        this.debug = debug;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("get_account")
    public String getAccount;

    public CallbackUrls withGetAccount(String getAccount) {
        this.getAccount = getAccount;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mobile_app_domain")
    public String mobileAppDomain;

    public CallbackUrls withMobileAppDomain(String mobileAppDomain) {
        this.mobileAppDomain = mobileAppDomain;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("oauth_logout")
    public String oauthLogout;

    public CallbackUrls withOauthLogout(String oauthLogout) {
        this.oauthLogout = oauthLogout;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("oauth_redirect")
    public String oauthRedirect;

    public CallbackUrls withOauthRedirect(String oauthRedirect) {
        this.oauthRedirect = oauthRedirect;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("privacy_policy")
    public String privacyPolicy;

    public CallbackUrls withPrivacyPolicy(String privacyPolicy) {
        this.privacyPolicy = privacyPolicy;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("product_info")
    public String productInfo;

    public CallbackUrls withProductInfo(String productInfo) {
        this.productInfo = productInfo;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("remote_api")
    public String remoteApi;

    public CallbackUrls withRemoteApi(String remoteApi) {
        this.remoteApi = remoteApi;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("shipping")
    public String shipping;

    public CallbackUrls withShipping(String shipping) {
        this.shipping = shipping;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("support_page")
    public String supportPage;

    public CallbackUrls withSupportPage(String supportPage) {
        this.supportPage = supportPage;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tax")
    public String tax;

    public CallbackUrls withTax(String tax) {
        this.tax = tax;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("terms_of_service")
    public String termsOfService;

    public CallbackUrls withTermsOfService(String termsOfService) {
        this.termsOfService = termsOfService;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("universal_merchant_api")
    public String universalMerchantApi;

    public CallbackUrls withUniversalMerchantApi(String universalMerchantApi) {
        this.universalMerchantApi = universalMerchantApi;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("update_cart")
    public String updateCart;

    public CallbackUrls withUpdateCart(String updateCart) {
        this.updateCart = updateCart;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("validate_additional_account_data")
    public String validateAdditionalAccountData;

    public CallbackUrls withValidateAdditionalAccountData(String validateAdditionalAccountData) {
        this.validateAdditionalAccountData = validateAdditionalAccountData;
        return this;
    }
    
    public CallbackUrls(){}
}
