/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CartShipment {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("address")
    public Object address;

    public CartShipment withAddress(Object address) {
        this.address = address;
        return this;
    }
    
    /**
     * The name of the carrier selected.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("carrier")
    public String carrier;

    public CartShipment withCarrier(String carrier) {
        this.carrier = carrier;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cost")
    public Amounts cost;

    public CartShipment withCost(Amounts cost) {
        this.cost = cost;
        return this;
    }
    
    public CartShipment(){}
}
