/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class Cart {
    @JsonProperty("amounts")
    public Amounts amounts;

    public Cart withAmounts(Amounts amounts) {
        this.amounts = amounts;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("discounts")
    public CartDiscount[] discounts;

    public Cart withDiscounts(CartDiscount[] discounts) {
        this.discounts = discounts;
        return this;
    }
    
    /**
     * This field corresponds to the merchant's order reference associated with this Bolt transaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("display_id")
    public String displayId;

    public Cart withDisplayId(String displayId) {
        this.displayId = displayId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("items")
    public CartItem[] items;

    public Cart withItems(CartItem[] items) {
        this.items = items;
        return this;
    }
    
    /**
     * Used optionally to pass additional information like order numbers or other IDs as needed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("order_description")
    public String orderDescription;

    public Cart withOrderDescription(String orderDescription) {
        this.orderDescription = orderDescription;
        return this;
    }
    
    /**
     * This value is used by Bolt as an external reference to a given order. This reference must be unique per successful transaction.
     */
    @JsonProperty("order_reference")
    public String orderReference;

    public Cart withOrderReference(String orderReference) {
        this.orderReference = orderReference;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("shipments")
    public CartShipment[] shipments;

    public Cart withShipments(CartShipment[] shipments) {
        this.shipments = shipments;
        return this;
    }
    
    public Cart(@JsonProperty("amounts") Amounts amounts, @JsonProperty("order_reference") String orderReference) {
        this.amounts = amounts;
        this.orderReference = orderReference;
  }
}
