/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Error - The specified resource was not found
 */

public class Error {
    /**
     * The type of error returned
     */
    @JsonProperty(".tag")
    public String dotTag;

    public Error withDotTag(String dotTag) {
        this.dotTag = dotTag;
        return this;
    }
    
    /**
     * A human-readable error message, which might include information specific to
     * the request that was made.
     * 
     */
    @JsonProperty("message")
    public String message;

    public Error withMessage(String message) {
        this.message = message;
        return this;
    }
    
    public Error(@JsonProperty(".tag") String dotTag, @JsonProperty("message") String message) {
        this.dotTag = dotTag;
        this.message = message;
  }
}
