/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum EventListTag {
    LIST("list");

    @JsonValue
    public final String value;

    private EventListTag(String value) {
        this.value = value;
    }
}
