/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class EventGroup {
    @JsonProperty(".tag")
    public EventGroupTag dotTag;

    public EventGroup withDotTag(EventGroupTag dotTag) {
        this.dotTag = dotTag;
        return this;
    }
    
    @JsonProperty("event_group")
    public EventGroupEventGroup eventGroup;

    public EventGroup withEventGroup(EventGroupEventGroup eventGroup) {
        this.eventGroup = eventGroup;
        return this;
    }
    
    public EventGroup(@JsonProperty(".tag") EventGroupTag dotTag, @JsonProperty("event_group") EventGroupEventGroup eventGroup) {
        this.dotTag = dotTag;
        this.eventGroup = eventGroup;
  }
}
