/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum EventGroupEventGroup {
    ALL("all");

    @JsonValue
    public final String value;

    private EventGroupEventGroup(String value) {
        this.value = value;
    }
}
