/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum EventGroupTag {
    GROUP("group");

    @JsonValue
    public final String value;

    private EventGroupTag(String value) {
        this.value = value;
    }
}
