/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class EventList {
    @JsonProperty(".tag")
    public EventListTag dotTag;

    public EventList withDotTag(EventListTag dotTag) {
        this.dotTag = dotTag;
        return this;
    }
    
    @JsonProperty("event_list")
    public EventListEventList[] eventList;

    public EventList withEventList(EventListEventList[] eventList) {
        this.eventList = eventList;
        return this;
    }
    
    public EventList(@JsonProperty(".tag") EventListTag dotTag, @JsonProperty("event_list") EventListEventList[] eventList) {
        this.dotTag = dotTag;
        this.eventList = eventList;
  }
}
