/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class GuestPaymentMethodInitializeRequest {
    @JsonProperty("cart")
    public Cart cart;

    public GuestPaymentMethodInitializeRequest withCart(Cart cart) {
        this.cart = cart;
        return this;
    }
    
    @JsonProperty("payment_method")
    public PaymentMethodPaypal paymentMethod;

    public GuestPaymentMethodInitializeRequest withPaymentMethod(PaymentMethodPaypal paymentMethod) {
        this.paymentMethod = paymentMethod;
        return this;
    }
    
    public GuestPaymentMethodInitializeRequest(@JsonProperty("cart") Cart cart, @JsonProperty("payment_method") PaymentMethodPaypal paymentMethod) {
        this.cart = cart;
        this.paymentMethod = paymentMethod;
  }
}
