/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Identifiers - Identifiers were successfully retrieved
 */

public class Identifiers {
    @JsonProperty("merchant_divisions")
    public IdentifiersMerchantDivisions[] merchantDivisions;

    public Identifiers withMerchantDivisions(IdentifiersMerchantDivisions[] merchantDivisions) {
        this.merchantDivisions = merchantDivisions;
        return this;
    }
    
    @JsonProperty("merchant_id")
    public String merchantId;

    public Identifiers withMerchantId(String merchantId) {
        this.merchantId = merchantId;
        return this;
    }
    
    @JsonProperty("signing_secret")
    public String signingSecret;

    public Identifiers withSigningSecret(String signingSecret) {
        this.signingSecret = signingSecret;
        return this;
    }
    
    public Identifiers(@JsonProperty("merchant_divisions") IdentifiersMerchantDivisions[] merchantDivisions, @JsonProperty("merchant_id") String merchantId, @JsonProperty("signing_secret") String signingSecret) {
        this.merchantDivisions = merchantDivisions;
        this.merchantId = merchantId;
        this.signingSecret = signingSecret;
  }
}
