/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * IdentifierIdentifierType - The type of identifier
 */
public enum IdentifierIdentifierType {
    EMAIL("email"),
    EMAIL_SHA256("email_sha256");

    @JsonValue
    public final String value;

    private IdentifierIdentifierType(String value) {
        this.value = value;
    }
}
