/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class PaymentMethodSavedPaymentMethod {
    @JsonProperty(".tag")
    public PaymentMethodSavedPaymentMethodTag dotTag;

    public PaymentMethodSavedPaymentMethod withDotTag(PaymentMethodSavedPaymentMethodTag dotTag) {
        this.dotTag = dotTag;
        return this;
    }
    
    /**
     * Payment ID of the saved Bolt Payment method.
     */
    @JsonProperty("id")
    public String id;

    public PaymentMethodSavedPaymentMethod withId(String id) {
        this.id = id;
        return this;
    }
    
    public PaymentMethodSavedPaymentMethod(@JsonProperty(".tag") PaymentMethodSavedPaymentMethodTag dotTag, @JsonProperty("id") String id) {
        this.dotTag = dotTag;
        this.id = id;
  }
}
