/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class PaymentMethodInitializeResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("action")
    public PaymentMethodInitializeResponseAction action;

    public PaymentMethodInitializeResponse withAction(PaymentMethodInitializeResponseAction action) {
        this.action = action;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public String id;

    public PaymentMethodInitializeResponse withId(String id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    public PaymentMethodInitializeResponseStatus status;

    public PaymentMethodInitializeResponse withStatus(PaymentMethodInitializeResponseStatus status) {
        this.status = status;
        return this;
    }
    
    public PaymentMethodInitializeResponse(){}
}
