/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum PaymentMethodInitializeResponseStatus {
    AWAITING_USER_CONFIRMATION("awaiting_user_confirmation"),
    PAYMENT_READY("payment_ready"),
    UPDATE_PAYMENT_METHOD("update_payment_method"),
    SUCCESS("success");

    @JsonValue
    public final String value;

    private PaymentMethodInitializeResponseStatus(String value) {
        this.value = value;
    }
}
