/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class PaymentMethodInitializeResponseAction {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("method")
    public PaymentMethodInitializeResponseActionMethod method;

    public PaymentMethodInitializeResponseAction withMethod(PaymentMethodInitializeResponseActionMethod method) {
        this.method = method;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    public PaymentMethodInitializeResponseActionType type;

    public PaymentMethodInitializeResponseAction withType(PaymentMethodInitializeResponseActionType type) {
        this.type = type;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("url")
    public String url;

    public PaymentMethodInitializeResponseAction withUrl(String url) {
        this.url = url;
        return this;
    }
    
    public PaymentMethodInitializeResponseAction(){}
}
