/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum PaymentMethodCreditCardTag {
    CREDIT_CARD("credit_card");

    @JsonValue
    public final String value;

    private PaymentMethodCreditCardTag(String value) {
        this.value = value;
    }
}
