/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum PaymentMethodInitializeResponseActionType {
    REDIRECT("redirect"),
    FINALIZE("finalize");

    @JsonValue
    public final String value;

    private PaymentMethodInitializeResponseActionType(String value) {
        this.value = value;
    }
}
