/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum PaymentMethodInitializeResponseActionMethod {
    GET("GET"),
    POST("POST");

    @JsonValue
    public final String value;

    private PaymentMethodInitializeResponseActionMethod(String value) {
        this.value = value;
    }
}
