/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class PaymentMethodCreditCard {
    @JsonProperty(".tag")
    public PaymentMethodCreditCardTag dotTag;

    public PaymentMethodCreditCard withDotTag(PaymentMethodCreditCardTag dotTag) {
        this.dotTag = dotTag;
        return this;
    }
    
    /**
     * The ID of credit card's billing address
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("billing_address_id")
    public String billingAddressId;

    public PaymentMethodCreditCard withBillingAddressId(String billingAddressId) {
        this.billingAddressId = billingAddressId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("billing_address_input")
    public Object billingAddressInput;

    public PaymentMethodCreditCard withBillingAddressInput(Object billingAddressInput) {
        this.billingAddressInput = billingAddressInput;
        return this;
    }
    
    /**
     * The Bank Identification Number for the credit card. This is typically the first 4-6 digits of the credit card number.
     */
    @JsonProperty("bin")
    public String bin;

    public PaymentMethodCreditCard withBin(String bin) {
        this.bin = bin;
        return this;
    }
    
    /**
     * The expiration date of the credit card. TODO TO MAKE EXPIRATION REUSABLE
     */
    @JsonProperty("expiration")
    public String expiration;

    public PaymentMethodCreditCard withExpiration(String expiration) {
        this.expiration = expiration;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public String id;

    public PaymentMethodCreditCard withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The last 4 digits of the credit card number.
     */
    @JsonProperty("last4")
    public String last4;

    public PaymentMethodCreditCard withLast4(String last4) {
        this.last4 = last4;
        return this;
    }
    
    /**
     * The credit card network.
     */
    @JsonProperty("network")
    public PaymentMethodCreditCardNetwork network;

    public PaymentMethodCreditCard withNetwork(PaymentMethodCreditCardNetwork network) {
        this.network = network;
        return this;
    }
    
    /**
     * The Bolt token associated to the credit card.
     */
    @JsonProperty("token")
    public String token;

    public PaymentMethodCreditCard withToken(String token) {
        this.token = token;
        return this;
    }
    
    /**
     * Credit card type
     */
    @JsonProperty("type")
    public PaymentMethodCreditCardType type;

    public PaymentMethodCreditCard withType(PaymentMethodCreditCardType type) {
        this.type = type;
        return this;
    }
    
    public PaymentMethodCreditCard(@JsonProperty(".tag") PaymentMethodCreditCardTag dotTag, @JsonProperty("bin") String bin, @JsonProperty("expiration") String expiration, @JsonProperty("last4") String last4, @JsonProperty("network") PaymentMethodCreditCardNetwork network, @JsonProperty("token") String token, @JsonProperty("type") PaymentMethodCreditCardType type) {
        this.dotTag = dotTag;
        this.bin = bin;
        this.expiration = expiration;
        this.last4 = last4;
        this.network = network;
        this.token = token;
        this.type = type;
  }
}
