/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PaymentMethodCreditCardType - Credit card type
 */
public enum PaymentMethodCreditCardType {
    CREDIT("credit"),
    PLCC("plcc");

    @JsonValue
    public final String value;

    private PaymentMethodCreditCardType(String value) {
        this.value = value;
    }
}
