/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ShipmentTrackingUpdateSchemasStatus {
    UNKNOWN("unknown"),
    PRE_TRANSIT("pre_transit"),
    IN_TRANSIT("in_transit"),
    OUT_FOR_DELIVERY("out_for_delivery"),
    DELIVERED("delivered"),
    AVAILABLE_FOR_PICKUP("available_for_pickup"),
    RETURN_TO_SENDER("return_to_sender"),
    FAILURE("failure"),
    CANCELLED("cancelled"),
    ERROR("error");

    @JsonValue
    public final String value;

    private ShipmentTrackingUpdateSchemasStatus(String value) {
        this.value = value;
    }
}
