/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ShipmentTrackingUpdateStatus - The shipment's status.
 */
public enum ShipmentTrackingUpdateStatus {
    IN_TRANSIT("in_transit"),
    CANCELLED("cancelled"),
    FAILURE("failure"),
    DELIVERED("delivered");

    @JsonValue
    public final String value;

    private ShipmentTrackingUpdateStatus(String value) {
        this.value = value;
    }
}
