/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.bolt.bolt_embed.utils.DateTimeDeserializer;
import com.bolt.bolt_embed.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;


public class ShipmentTrackingUpdate {
    /**
     * The shipment's actual or estimated delivery date.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("delivery_date")
    public OffsetDateTime deliveryDate;

    public ShipmentTrackingUpdate withDeliveryDate(OffsetDateTime deliveryDate) {
        this.deliveryDate = deliveryDate;
        return this;
    }
    
    /**
     * The shipment's status.
     */
    @JsonProperty("status")
    public ShipmentTrackingUpdateStatus status;

    public ShipmentTrackingUpdate withStatus(ShipmentTrackingUpdateStatus status) {
        this.status = status;
        return this;
    }
    
    /**
     * A list of tracking updates that contain the shipment's status, location, and any unique messages.
     */
    @JsonProperty("tracking_details")
    public ShipmentTrackingUpdateTrackingDetails[] trackingDetails;

    public ShipmentTrackingUpdate withTrackingDetails(ShipmentTrackingUpdateTrackingDetails[] trackingDetails) {
        this.trackingDetails = trackingDetails;
        return this;
    }
    
    /**
     * The carrier's tracking number for the shipment. Must be prefixed with `MockBolt`.
     */
    @JsonProperty("tracking_number")
    public String trackingNumber;

    public ShipmentTrackingUpdate withTrackingNumber(String trackingNumber) {
        this.trackingNumber = trackingNumber;
        return this;
    }
    
    public ShipmentTrackingUpdate(@JsonProperty("status") ShipmentTrackingUpdateStatus status, @JsonProperty("tracking_details") ShipmentTrackingUpdateTrackingDetails[] trackingDetails, @JsonProperty("tracking_number") String trackingNumber) {
        this.status = status;
        this.trackingDetails = trackingDetails;
        this.trackingNumber = trackingNumber;
  }
}
