/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class TrackingDetails {
    /**
     * The country associated this this set of tracking details, if any.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("country_code")
    public String countryCode;

    public TrackingDetails withCountryCode(String countryCode) {
        this.countryCode = countryCode;
        return this;
    }
    
    /**
     * The tracking detail's timestamp.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("event_date")
    public String eventDate;

    public TrackingDetails withEventDate(String eventDate) {
        this.eventDate = eventDate;
        return this;
    }
    
    /**
     * The locality associated this this set of tracking details, if any.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("locality")
    public String locality;

    public TrackingDetails withLocality(String locality) {
        this.locality = locality;
        return this;
    }
    
    /**
     * An arbitrary, human-readable message associated with this set of tracking details.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("message")
    public String message;

    public TrackingDetails withMessage(String message) {
        this.message = message;
        return this;
    }
    
    /**
     * The postal associated this this set of tracking details, if any.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("postal_code")
    public String postalCode;

    public TrackingDetails withPostalCode(String postalCode) {
        this.postalCode = postalCode;
        return this;
    }
    
    /**
     * The region associated this this set of tracking details, if any.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("region")
    public String region;

    public TrackingDetails withRegion(String region) {
        this.region = region;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    public ShipmentTrackingUpdateSchemasStatus status;

    public TrackingDetails withStatus(ShipmentTrackingUpdateSchemasStatus status) {
        this.status = status;
        return this;
    }
    
    public TrackingDetails(){}
}
