/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.bolt.bolt_embed.utils.DateTimeDeserializer;
import com.bolt.bolt_embed.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

/**
 * Webhook - The webhook was successfully created
 */

public class Webhook {
    /**
     * The time at which the webhook was created
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created_at")
    public OffsetDateTime createdAt;

    public Webhook withCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }
    
    @JsonProperty("event")
    public Object event;

    public Webhook withEvent(Object event) {
        this.event = event;
        return this;
    }
    
    /**
     * The webhook's ID
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public String id;

    public Webhook withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The webhook's URL
     */
    @JsonProperty("url")
    public String url;

    public Webhook withUrl(String url) {
        this.url = url;
        return this;
    }
    
    public Webhook(@JsonProperty("event") Object event, @JsonProperty("url") String url) {
        this.event = event;
        this.url = url;
  }
}
