/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.bolt.bolt_embed.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class WebhookInput {
    @JsonProperty("event")
    public Object event;

    public WebhookInput withEvent(Object event) {
        this.event = event;
        return this;
    }
    
    /**
     * The webhook's URL
     */
    @JsonProperty("url")
    public String url;

    public WebhookInput withUrl(String url) {
        this.url = url;
        return this;
    }
    
    public WebhookInput(@JsonProperty("event") Object event, @JsonProperty("url") String url) {
        this.event = event;
        this.url = url;
  }
}
